# Generated by Django 2.0.4 on 2018-05-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20180512_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_amount', models.IntegerField()),
                ('destination_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferItemParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='ledger.Person')),
                ('transfer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ledger.TransferItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='transferparticipant',
            name='person',
        ),
        migrations.RemoveField(
            model_name='transferparticipant',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='destination_amount',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='source_amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.TransactionGroup'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='statement_position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='ledger.StatementRow'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='ledger.Transaction'),
        ),
        migrations.DeleteModel(
            name='TransferParticipant',
        ),
        migrations.AddField(
            model_name='transferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledger.Transfer'),
        ),
    ]
