# Generated by Django 2.0.4 on 2018-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20180522_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferitem',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
