# Generated by Django 2.0.4 on 2018-05-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_transferitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='group',
        ),
        migrations.AddField(
            model_name='transferitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='ledger.TransactionGroup'),
        ),
    ]
