# Generated by Django 2.0.4 on 2018-11-24 19:18

from django.db import migrations, models
import re

def set_default_reference(apps, schema_editor):
    invalid_char = re.compile('[^A-Z0-9]')
    TransactionGroup = apps.get_model('ledger', 'TransactionGroup')
    for group in TransactionGroup.objects.all().iterator():
        group.reference = invalid_char.sub('', group.name)
        group.save()

def unset_default_reference(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20180522_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongroup',
            name='reference',
            field=models.CharField(max_length=20, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_reference, unset_default_reference),
        migrations.AlterField(
            model_name='transactiongroup',
            name='reference',
            field=models.CharField(max_length=20, null=False, unique=True),
            preserve_default=False,
        ),
    ]
