# Generated by Django 2.1.5 on 2019-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20181201_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
    ]
